[package]
name = "compute"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytemuck = "1.21.0"
crossbeam-channel = "0.5.14"
encase = { version = "0.10.0", features = ["nalgebra"] }
nalgebra = "0.33.2"
pollster = "0.4.0"
wgpu = "23.0.1"

# Interactive only
egui = "0.30.0"
egui-wgpu = "0.30.0"
egui-winit = "0.30.0"
winit = "0.30.7"

[workspace]
members = [
    "examples/basic",
    "examples/mandelbrot",
    "examples/mandelbrot-interactive",
]
