[package]
name = "texture-mapping"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "texture-mapping"
path = "main.rs"

[dependencies]
tufa = { path = "../..", features = ["interactive"] }

anyhow = "1.0.95"
encase = { version = "0.10.0", features = ["nalgebra"] }
image = "0.25.6"
